version: "13.0.0"
name: libation
base: core24
summary: Liberate your audio books
description: |
  Libation is a free, open source audible library manager. 
  Decrypt, backup, organize, and search your audible library
platforms:
  amd64:
  arm64:
  
grade: stable
confinement: strict

parts:
  libation:
    source: https://github.com/rmcrackan/Libation/releases/download/v$SNAPCRAFT_PROJECT_VERSION/Libation.$SNAPCRAFT_PROJECT_VERSION-linux-chardonnay-$CRAFT_ARCH_BUILD_FOR.deb
    plugin: dump
    override-pull: |
      echo $SNAPCRAFT_PROJECT_VERSION
      echo $CRAFT_ARCH_BUILD_FOR
      echo https://github.com/rmcrackan/Libation/releases/download/v$SNAPCRAFT_PROJECT_VERSION/Libation.$SNAPCRAFT_PROJECT_VERSION-linux-chardonnay-$CRAFT_ARCH_BUILD_FOR.deb
      craftctl default
    stage-packages:
      - libgtk-3-0
      - libwebkit2gtk-4.1-0

apps:
  libation:
    command: usr/lib/libation/Libation
    extensions: [gnome]
    environment:
      HOME: "$SNAP_USER_COMMON"
    plugs:
      - network
      - home
      - removable-media
